---
- hosts: docker-students

  vars:
    hugo_version: 0.16

  tasks:
    - file: path=/home/student/docs/data state=directory mode=0755  

    - synchronize: src=./ dest=/home/student/docs/

    - name: download hugo
      get_url:
        url: "https://github.com/spf13/hugo/releases/download/\
              v{{ hugo_version }}/hugo_{{ hugo_version }}_linux-64bit.tgz"
        dest: /tmp/hugo.tar.gz

    - unarchive: src=/tmp/hugo.tar.gz dest=/tmp copy=no

    - command: mv /tmp/hugo /usr/local/bin
               creates=/usr/local/bin/hugo
      notify: restart hugo

    - template: src=hosts.yml.j2 dest=/home/student/docs/data/hosts.yml

    - template: src=hugo.conf.j2 dest=/etc/init/hugo.conf
      notify: restart hugo  

  handlers:
    - name: restart hugo
      service: name=hugo state=restarted
